apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
patchesStrategicMerge:
- deployment.yaml
- service.yaml
namespace: instavote
configMapGenerator:
- name: vote
  literals:
    - OPTION_A=STAGING
    - OPTION_B=DEV
